name: test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer

jobs:
  test:
    runs-on: macOS-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test Build
        run: swift build

