name: test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_26.0.1.app/Contents/Developer

jobs:
  test:
    runs-on: macos-26
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test Build
        run: swift build -Xswiftc -warnings-as-errors --enable-experimental-prebuilts

