name: test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_26.app/Contents/Developer

jobs:
  test:
    runs-on: macos-26
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test Build
        run: swift build -Xswiftc -warnings-as-errors --enable-experimental-prebuilts
  format:
    runs-on: macos-26
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run formatter
        run: sh .github/format.sh

      - name: Check if formatting changes exist
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Formatting changes detected."
            exit 1
          fi
